cross_val_n_repeats: 3
cross_val_n_splits: 5
cv_f1_plot_path: ../figs/cv_f1_plot_5k_features_SmoteTomek.png
cv_results_path: ../outputs/cv_results_5k_features_SmoteTomek.csv
cv_results_plot_path: ../figs/cv_results_plot_5k_features_SmoteTomek.png
decision_tree_min_samples_split: 3
decision_tree_splitter: best
final_predictions_path: ../outputs/test_predictions_5k_features_SmoteTomek.csv
imbalance_method: SMOTETomek
k: 7000
multinomial_nb_alpha: 0.7
multinomial_nb_class_prior_0: 0.1
multinomial_nb_class_prior_1: 0.9
multinomial_nb_fit_prior: true
num_ftrs_final: 5000
num_trees: 5000
p: 0.99
perceptron_alpha: 0.01
perceptron_class_weight_0: 0.1
perceptron_class_weight_1: 0.9
perceptron_eta_0: 0.01
perceptron_fit_intercept: true
perceptron_max_iter: 3000
perceptron_penalty: l2
perceptron_shuffle: true
perceptron_tol: 0.001
random_state: 1337
test_path: ../data/test.txt
train_path: ../data/train.txt
