train_path: ../data/train.txt
test_path: ../data/test.txt
stump: decision_tree
cv_f1_plot_path: ../figs/adaboost_decision_tree_15_cv_f1_vs_k.png
final_predictions_path: ../outputs/adaboost_decision_tree_15.csv
imbalance_method: SMOTETomek
p: 0.99
k: 7000
num_trees: 5000
num_ftrs_final: 5000
num_learners:
  - 3
  - 5
  - 10
  - 15
  - 20
  - 25
  - 30
  - 35
  - 40
  - 45
  - 50
  - 100
  # - 150
  # - 200
  # - 250
  # - 300
  # - 350
  # - 400
  # - 450
  # - 500
cross_val_n_splits: 5
cross_val_n_repeats: 3
random_state: 1337
metric: f1_macro
